FROM public.ecr.aws/lambda/python:3.8
COPY ./requirements.txt requirements.txt
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"
COPY ./get_data.py ${LAMBDA_TASK_ROOT}

CMD ["get_data.handler"]